# https://taskfile.dev

version: '3'

tasks:

  start:
    desc: Run the webserver
    cmds:
      - go run .

  dev:
    desc: Run the ui development server
    cmds:
      - npm install
      - npm start

  build:
    desc: Build the ui application
    cmds:
      - npm run build
